apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-list-ingress
  labels:
    name: my-list-ingress
spec:
  rules:
    - http:
        paths:
        - path: /identity
          pathType: Prefix
          backend:
            service:
              name: identity-api-service
              port: 
                number: 80