apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-list-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: my-list-ingress
spec:
  rules:
  - host: identitytestes1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identity-api-service
            port: 
              number: 80