version: '3.4'

services:
  sqldata:
    env_file: ./Environments/SqlServer/.env
    ports:
      - "1433:1433"
      
  identity-api:
    env_file: ./Environments/Identity/.env
    restart: always
    ports:
      - "5570:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  purchaseList-api:
    env_file: ./Environments/PurchaseList/.env
    restart: always
    ports:
      - "5580:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
