apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          - name: ACCEPT_EULA
            valueFrom:
              secretKeyRef:
                name: sql-server-secret 
                key: ACCEPT_EULA

          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-server-secret 
                key: SA_PASSWORD  
        volumeMounts:
          - mountPath: "var/lib/sqlServer"
            name: sql-server-volume
        ports:
        - containerPort: 1433
          name: sql-server
      volumes:
        - name: sql-server-volume
          persistentVolumeClaim:
            claimName: sql-server-pvc