name: .NET CI

on:
   push:
    branches: 
     - master 
     - develop
   pull_request:
    branches: 
     - master 
     - develop

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      ROOT_PATH: ./src/Server/Services/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        no_push: ${{ github.event_name == 'push' }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Services
      run: docker-compose build
      working-directory: ./src/Docker/
      
    - name: Dotnet Tests
      run: dotnet test MyList.sln --no-build --verbosity normal
      working-directory: ./src

    - name: Push Identity Service
      id: docker_build_identity_service
      uses: docker/build-push-action@v2
      with:
       file: ${{env.ROOT_PATH}}Identity/Identity.API/Dockerfile
       push: true
       tags: "${{ secrets.DOCKER_USER }}/identity-api:v${{ github.run_id }}, ${{ secrets.DOCKER_USER }}/identity-api:latest" 
       
    - name: Push PurchaseList Service
      id: docker_build_puchase_list_service
      uses: docker/build-push-action@v2
      with:
       push: true
       file: ${{env.ROOT_PATH}}PurchaseList/PurchaseList.API/Dockerfile
       tags: "${{ secrets.DOCKER_USER }}/purchase-list-api:v${{ github.run_id }}, ${{ secrets.DOCKER_USER }}/purchase-list-api:latest"
       

