name: .NET CI

on:
   push:
    branches: 
     - master 
     - develop
     - feature/configure-ci-docker
   pull_request:
    branches: 
     - master 
     - develop
     - feature/configure-ci-docker

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      ROOT_PATH: ./src/Server/Services/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # - name: Build Services
    #   run: docker-compose up -d --build
    #   working-directory: ./src

    - name: Push and Build Identity Service
      id: docker_build_identity_service
      uses: docker/build-push-action@v2
      with:
       context: ./
       file: ${{env.ROOT_PATH}}Identity/Identity.API/Dockerfile
       push: true
       tags: ${{ secrets.DOCKER_USER }}/my-list:identity-api-v${{ github.run_id }}

    - name: Push and Build PurchaseList Service
      id: docker_build_puchase_list_service
      uses: docker/build-push-action@v2
      with:
       context: ./
       file: ${{env.ROOT_PATH}}PurchaseList/PurchaseList.API/Dockerfile
       push: true
       tags: ${{ secrets.DOCKER_USER }}/my-list:purchase-list-api-v${{ github.run_id }}

    - name: Dotnet Tests
      run: dotnet test MyList.sln --no-build --verbosity normal
      working-directory: ./src

