name: .NET CI

on:
   push:
    branches: 
     - master 
     - develop
   pull_request:
    branches: 
     - master 
     - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore MyList.sln
      working-directory: ./src

    - name: Build
      run: dotnet build MyList.sln --no-restore
      working-directory: ./src
      
    - name: Test
      run: dotnet test MyList.sln --no-build --verbosity normal
      working-directory: ./src
