name: .NET CI

on:
   push:
    branches: 
     - master 
     - develop
     - feature/configure-ci-docker
   pull_request:
    branches: 
     - master 
     - develop
     - feature/configure-ci-docker
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Services
      run: docker-compose up -d --build
      working-directory: ./src

    - name: Finish 
      run: docker-compose down
      working-directory: ./src

    - name: Build
      run: dotnet build MyList.sln --no-restore
      working-directory: ./src
      
    - name: Test
      run: dotnet test MyList.sln --no-build --verbosity normal
      working-directory: ./src
